using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace gasoilin_project_v2.Pages
{
    public class HistoryModel : PageModel
    {
        public class TimelineEvent
        {
            public string Year { get; set; }
            public string Title { get; set; }
            public string Description { get; set; }

            public TimelineEvent(string year, string title, string description)
            {
                Year = year;
                Title = title;
                Description = description;
            }
        }

        public List<TimelineEvent> TimelineEvents { get; set; } = new List<TimelineEvent>();

        public void OnGet()
        {
            // Populate the timeline events
            TimelineEvents.Add(new TimelineEvent("1969", "Bandets oprindelse og medlemmernes baggrund",
                "Gasolin’ blev dannet i 1969 i det københavnske kvarter Christianshavn af Kim Larsen, Franz Beckerlee og Wili Jønsson. Bandnavnet kom fra en beboer i deres kollektiv, som foreslog “Gasoline” (amerikansk for benzin) – idéen var at bandets musik skulle “tanke folk op” – og det endelige navn blev Gasolin’ (apostroffen i stedet for “e”)\r\n\r\n\t\t\t. Kim Larsen (1945–2018) var forsanger, guitarist og sangskriver, Franz Beckerlee (f. 1942) spillede guitar, og Wili Jønsson (f. 1942) tog sig af bas, keyboard og kor. Deres første trommeslager var Bjørn Uglebjerg (1948–1994), som i 1971 blev erstattet af Søren “Charlie” Berlev (f. 1950). Beckerlee og Jønsson kendte hinanden fra barndommen, og de to fandt sammen om musikken; Kim Larsen sluttede sig til efter at have svaret på en opslagsseddel. Det tidlige Gasolin’-miljø var præget af Christianshavns frie atmosfære og hippiekultur – medlemmerne boede bl.a. i kollektiver som Sofiegården og deltog i ungdomsoprørets aktiviteter, hvilket senere afspejledes i deres tekster. Christianshavn forblev bandets base og inspirationskilde gennem hele deres levetid."));

            TimelineEvents.Add(new TimelineEvent("1970-1971", "Musikalsk udvikling og inspirationer",
                "Gasolin’s musikalske rødder spændte bredt fra international rock til danske vise-traditioner. I begyndelsen var Franz Beckerlee stærkt inspireret af Jimi Hendrix’ syrede guitarsoloer, mens Kim Larsen fandt inspiration i Bob Dylans sangskrivning og folk-stil. Wili Jønsson og Søren Berlev bidrog med en solid rytmesektion formet af kærlighed til The Beatles’ melodiske rock. Kombinationen af Larsens sans for iørefaldende popmelodier, Beckerlees kunstneriske eksperimenter og Jønssons musikalske håndværk skabte hurtigt Gasolins egen stil. I deres første år skrev de primært engelsksprogede sange for at ramme et internationalt publikum, men de første singler – “Silky Sally”, “Child of Institution” og “Johnny The Jackpot” (1970-71) – floppede alle. Erfaringen lærte dem, at de udtrykte sig bedre på dansk, hvor sproget gav dem en unik evne til at kommunikere med publikum. Fra 1971 skiftede de til at skrive på dansk, hvilket straks blev belønnet med både publikums og anmelderes anerkendelse. Bandet blandede energisk rock med elementer af pop og folkemusik, og deres sange afspejlede ofte samtidens sociale og politiske realiteter. Flere af deres tekster indeholdt samfundskommentarer om fx uretfærdighed og personlig frihed, hvilket gav Gasolin’ et rebelsk image. Den tidsånd og de miljøer, de færdedes i – fra Christianshavns brosten til ungdomsoprørets frontlinje – blev forvandlet til musikalsk brændstof i Gasolins udvikling."));

            TimelineEvents.Add(new TimelineEvent("1971-1973", "Debut og gennembrud (1971–1973)",
                "Gasolin’ fik for alvor vind i sejlene, da de overgik til danske tekster. I oktober 1971 udkom deres første album, “Gasolin’” (ofte kaldet Gas 1)\r\n\t\t\t. Albummet blev til på kun 10 dage i studiet og mixet i de berømte Trident Studios i London, hvilket vidner om bandets fokus og drive\r\n\t\t\t. Gasolin’ (1971) blev godt modtaget – publikum faldt for de mundrette danske tekster og muntre ordspil (forfattet af Larsen i samarbejde med vennen Mogens Mogensen) kombineret med det medrivende guitarspil og de enkle, sangbare melodier. Sange som “Langebro” – en stemningsfuld hyldest til Christianshavns ikoniske bro – demonstrerede bandets evne til at skabe både melankoli og fællessang på dansk jord. I 1972 fulgte andet album “Gasolin’ 2”, indspillet under tumultariske omstændigheder. Midt under indspilningerne forsøgte Larsen og Beckerlee sammen med andre beboere at forhindre nedrivningen af det besatte hus Stærekassen på Christianshavn – forgæves. Oplevelsen inspirerede Kim Larsen til protestsangen “Hva’ gør vi nu, lille du?”, der senere blev et af bandets kendte numre. Gasolin’ 2 (1972) fortsatte den opadgående kurve og bød bl.a. på sangen “Snehvide”, hvor bandet legede med eventyrmetaforer i et nutidigt lys. Allerede her trådte Gasolin’s sociale bevidsthed og humor frem side om side.\r\n\t\t\tI november 1973 udkom “Gasolin’ 3”, som markerede Gasolins kunstneriske og kommercielle gennembrud. Albummet – deres første samarbejde med den britiske stjerneproducer Roy Thomas Baker – blev en klassiker og anses af mange for et hovedværk i dansk rockhistorie. Musikalsk løsrev Gasolin’ sig endnu mere på Gasolin’ 3; hvor de to første albums blandede rock og vise, turde de her udforske nye lydbilleder. Sangene strakte sig fra hård rock til smukke ballader, men fælles var den stærke melodiske kerne. Albummets ikoniske forside vakte også opsigt: en ung kvinde med favnen fuld af indkøbsvarer og trusserne nede om anklerne midt på en gade i San Francisco – et motiv taget fra et vægmaleri i København. Det kontroversielle cover blev årtier senere kåret som Danmarks bedste albumcover og endda foreviget på et frimærke. Gasolin’ 3 udkom også i en engelsksproget udgave for det internationale marked, men trods kvaliteterne slog den ikke an uden for Danmark."));

            TimelineEvents.Add(new TimelineEvent("1974-1975", "Kulmination i Danmark (1974–1975)",
                "Bandet hvilede ikke på laurbærrene. Senere i 1974 udsendte de “Stakkels Jim” (ofte kaldt Gas 4), der igen blev et hit i Danmark. Albummet rummede blandt andet fængende rocknumre og poetiske fortællinger – Gasolin’ finpudsede her balancen mellem hård rock og folkelig appel. En engelsk version (“The Last Jim”) blev også forsøgt, men heller ikke denne gjorde væsentligt indtryk internationalt. Det store gennembrud i hjemlandet kom i 1975 med albummet “Gas 5”, som blev Gasolins bedst sælgende udgivelse. Gas 5 indeholdt to af gruppens allerstørste hits: “Rabalderstræde” og “Kvinde min”, som siden er blevet ægte rock-evergreens i Danmark. “Rabalderstræde” – et energisk rocknummer opkaldt efter en fiktiv gade – blev et generationshit med sit billede af vild ungdom og frie nætter, mens den romantiske “Kvinde min” vandt hjerter som en af dansk rocks mest elskede kærlighedssange. Med disse sange blev Gasolin’ folkeeje og 1970’ernes ubestridt mest populære danske rockorkester. Gruppen solgte nu plader og koncertbilletter i et omfang, man ikke tidligere havde set herhjemme. Et vidnesbyrd om deres status var en dobbeltkoncert de spillede sammen med kollegerne Shu-bi-dua i marts 1974. Selvom de to grupper stod med lige store navne på plakaten, var Gasolin’ reelt hovednavnet og den største attraktion – et klart signal om Gasolins førerposition på rockscenen. "));

            TimelineEvents.Add(new TimelineEvent("1976-1977", "Drømmen om USA og udfordringer (1976–1977)",
                "Efter Gas 5 begyndte Gasolin’ at drømme om et internationalt gennembrud. De følte, at de havde nået toppen i Danmark og satte nu blikket mod især USA. Roy Thomas Baker fortsatte som producer på den næste danske plade “Efter endnu en dag” (1976, ofte kaldt Gas 6), der udkom samme år og viste bandet i en lidt mere moden og eftertænksom tone. Inden da udsendte de live-dobbeltalbummet “Live Sådan” (1976), optaget under deres travle turnéår. Gasolin’s koncert ved Idrætsparken i København den 1. juli 1976 samlede over 10.000 begejstrede fans – en af de største rockkoncerter i Danmark til dato. På det tidspunkt var Gasolin’ på toppen af deres popularitet, og nu skulle resten af verden erobres.\r\n\t\t\tBandet indspillede en engelsksproget version af Gas 5 specielt til USA, hvor de omdøbte albummet til “What a Lemon”. De finpudsede deres “Valby-engelsk” og allierede sig med CBS Records i forsøget på at bryde igennem. I efteråret 1976 drog Gasolin’ på turné i USA for at promovere What a Lemon, der faktisk fik positive anmeldelser fra amerikanske kritikere. Desværre udeblev det kommercielle gennembrud – albummet solgte kun omkring 20.000 eksemplarer i USA. Turnéen endte som en økonomisk fiasko, der kostede bandet dyrt (anslået 1,2 millioner kr.). Da Gasolin’ vendte hjem til Danmark, blev de mødt af blandede reaktioner: Fansene stod der stadig, men dele af pressen kritiserede bandet for at have “solgt ud” af deres værdier i jagten på international succes. Denne periode satte Gasolin’ under pres – drømmen om USA var bristet, og det sled på det interne sammenhold.\r\n\t\t\tTrods skuffelsen gav Gasolin’ ikke op med det samme. I slutningen af 1976 og begyndelsen af 1977 gik de i studiet igen for at arbejde på endnu et engelsksproget album, denne gang med den amerikanske producer Felix Pappalardi (kendt fra bl.a. Cream). Tekstforfatteren Steven Lemberg blev hentet ind for at bidrage med engelske sangtekster, i håbet om at give musikken et mere autentisk amerikansk præg. Indspilningerne resulterede i albummet “Killin’ Time”, som dog først blev udgivet sommeren 1978 og kun i Skandinavien (i Sverige under titlen Tivoli). Pladeselskabet i USA valgte at skrinlægge udgivelsen dér, da man ikke troede på salget efter fiaskoen med What a Lemon. Killin’ Time blev således Gasolins sidste studiealbum og det fjerde (og sidste) med engelske tekster. Albummet var et forsøg på at skabe en mere “amerikansk” rocklyd, men bandet selv var ikke tilfredse med Pappalardis endelige mix. I sidste ende mixede Franz Beckerlee pladen om til den version, der udkom. Selvom Killin’ Time rummer stærke sange, kom det først på gaden, da Gasolin’ praktisk talt var opløst, og det fik derfor ikke den opmærksomhed, bandets tidligere udgivelser havde nydt."));

            TimelineEvents.Add(new TimelineEvent("1978", "Opløsning og sidste koncerter (1978)",
                "Kombinationen af USA-skuffelsen, udmattelse og interne spændinger blev til sidst for meget for Gasolin’. Gennem hele bandets ni-årige historie havde der ulmet konflikter mellem medlemmerne – især mellem frontfiguren Kim Larsen og guitarist Franz Beckerlee. De to stærke personligheder var vidt forskellige: Beckerlee kom fra jazz- og kunstscenen og dyrkede lange, eksperimenterende guitarsoloer, mens Larsen var den jordnære trubadur, der ville synge folkelige sange. Paradoksalt nok var det netop spændingen mellem deres forskelligheder, der gav Gasolin’ meget af sin dynamik og særpræg, men også dét der sled dem op. I sommeren 1978 besluttede Gasolin’ at stoppe på toppen. Den 21. august 1978 gav de deres sidste koncert før opløsningen – i Folkets Park i Malmø, Sverige. På dette tidspunkt havde Gasolin’ faktisk opnået næsten samme stjernestatus i nabolandene Norge og Sverige som i Danmark. Afskedskoncerten i Malmø blev en følelsesladet begivenhed for de tusindvis af skandinaviske fans, der tog afsked med “deres” band. Wili Jønsson har senere humoristisk forklaret, at Gasolin’ simpelthen “løb tør for brændstof” – et bandmedlem ville hellere bruge tid i sin nye kolonihave, som han sagde med et glimt i øjet\r\n\t\t\t. Efter opløsningen forblev Gasolin’ standhaftigt imod alle idéer om gendannelse. Kun én enkelt gang, i 1982, optrådte alle fire originale medlemmer sammen igen, da de deltog i rockteater-forestillingen Gorilla Galla. Men nogen egentlig genforening blev det aldrig til, og med Kim Larsens død i 2018 er muligheden for en gendannelse definitivt forbi."));
        }
    }
}
